"""Pydantic models for the Hue v2 CLIP API.

Every resource method returns one of these instead of a bare dict, so field
access is checked and discoverable. Models tolerate unknown fields, which
keeps them working across bridge firmware updates.
"""

from huepy.models.common import (
    Color,
    ColorGamut,
    ColorTemperature,
    ColorXY,
    Dimming,
    HueErrorDetail,
    HueModel,
    HueResource,
    HueResponse,
    Metadata,
    MirekSchema,
    NamedResource,
    On,
    ResourceIdentifier,
    ResourceType,
    unwrap,
    unwrap_one,
)
from huepy.models.device import (
    Bridge,
    Device,
    DevicePower,
    PowerState,
    ProductData,
    TimeZone,
)
from huepy.models.event import (
    EventResource,
    EventType,
    HueEvent,
    parse_events,
)
from huepy.models.group import (
    BridgeHome,
    ResourceGroup,
    Room,
    Scene,
    ServiceGroup,
    Zone,
)
from huepy.models.light import (
    Alert,
    Effect,
    Effects,
    Gradient,
    GradientPoint,
    GroupedLight,
    GroupedLightLevel,
    Light,
    LightCommands,
    LightLevel,
    LightLevelReading,
    Powerup,
    Signaling,
    TimedEffects,
)
from huepy.models.sensor import (
    Button,
    ButtonReport,
    Contact,
    ContactReport,
    GroupedMotion,
    Motion,
    MotionReading,
    MotionReport,
    Sensitivity,
    Temperature,
    TemperatureReading,
    TemperatureReport,
)
from huepy.models.state import build_light_payload

__all__ = [
    "Alert",
    "Bridge",
    "BridgeHome",
    "Button",
    "ButtonReport",
    "Color",
    "ColorGamut",
    "ColorTemperature",
    "ColorXY",
    "Contact",
    "ContactReport",
    "Device",
    "DevicePower",
    "Dimming",
    "Effect",
    "Effects",
    "EventResource",
    "EventType",
    "Gradient",
    "GradientPoint",
    "GroupedLight",
    "GroupedLightLevel",
    "GroupedMotion",
    "HueErrorDetail",
    "HueEvent",
    "HueModel",
    "HueResource",
    "HueResponse",
    "Light",
    "LightCommands",
    "LightLevel",
    "LightLevelReading",
    "Metadata",
    "MirekSchema",
    "Motion",
    "MotionReading",
    "MotionReport",
    "NamedResource",
    "On",
    "PowerState",
    "Powerup",
    "ProductData",
    "ResourceGroup",
    "ResourceIdentifier",
    "ResourceType",
    "Room",
    "Scene",
    "Sensitivity",
    "ServiceGroup",
    "Signaling",
    "Temperature",
    "TemperatureReading",
    "TemperatureReport",
    "TimeZone",
    "TimedEffects",
    "Zone",
    "build_light_payload",
    "parse_events",
    "unwrap",
    "unwrap_one",
]
